version: '3'

services:
  vonk-web:
    image: simplifier/vonk:2.0.1
    env_file:
        - ./server/appsettings.env
        - ./server/logsettings.env
    volumes:
      - ./server/license:/app/license
    ports:
      - "${port:-8080}:4080"

  vonk-mongo-db:
      image: mongo:4.0.10
