version: '3'

services:
  vonk-web:
    image: simplifier/vonk:3.0.0-beta2
    volumes:
      - ./server/license:/app/license
      - ./server/appsettings.json:/app/appsettings.json
      - ./server/logsettings.json:/app/logsettings.json
      # - ./server/vonk-import:/app/vonk-import
    ports:
      - "${port:-8080}:4080"

  vonk-mongo-db:
      image: mongo:4.0.10
