# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
    build:
        machine:
            # Image has Python 3.7
            image: circleci/classic:201808-01

        working_directory: ~/repo

        steps:
          - checkout

          - run:
              name: "Switch to Python 3.7"
              command: |
                pyenv global 3.7.0
                python --version

          - run:
              name: Build fhirutil CLI
              command: ./scripts/build.sh
          - run:
              name: Pull Docker images
              command: |
                docker pull kidsfirstdrc/torinox:torinox.r4-latest

          - run:
              name: Run unit tests
              command: |
                source ./venv/bin/activate
                pytest tests

          - run:
              name: FHIR model validation
              command: |
                source ./venv/bin/activate
                fhirutil validate $(pwd)/site_root/ig.ini --clear_output --publisher_opts='-tx n/a'

          - run:
              name: 'Publish FHIR model to Simplifier.net'
              command: |
                  if [ $CIRCLE_BRANCH == 'master' ]; then
                    source ./venv/bin/activate
                    fhirutil publish ./site_root/input/resources/profiles --username=$SIMPLIFIER_USER --password=$SIMPLIFIER_PW
                    fhirutil publish ./site_root/input/resources/examples --username=$SIMPLIFIER_USER --password=$SIMPLIFIER_PW
                  fi
