# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
    build:
        machine:
            # Image has Python 3.7
            image: circleci/classic:201808-01

        working_directory: ~/repo

        steps:
          - checkout

          - run:
              name: "Switch to Python 3.7"
              command: |
                pyenv global 3.7.0
                python --version

          - run:
              name: Build fhirmodel CLI
              command: ./scripts/build.sh
          - run:
              name: Pull Torinox image
              command: docker pull kidsfirstdrc/torinox:torinox-1.0.2

          - run:
              name: Create FHIR server files
              command: |
                source ./venv/bin/activate
                mkdir ./server/license
                echo $FHIR_SERVER_LICENSE > ./server/license/vonk-trial-license.json

          - run:
              name: Spin up FHIR server and db
              command: |
                docker-compose up -d
                until curl http://127.0.0.1:8080; do
                      >&2 echo "FHIR server is unavailable - sleeping"
                    sleep 5
                done
                >&2 echo "FHIR server is up"

          - run:
              name: Run unit tests
              command: |
                source ./venv/bin/activate
                pytest tests

          - run:
              name: FHIR model validation
              command: |
                source ./venv/bin/activate
                fhirmodel validate profile
                fhirmodel validate resource
                docker-compose down

          - run:
              name: 'Publish FHIR model to Simplifier.net'
              command: |
                  if [ $CIRCLE_BRANCH == 'master' ]; then
                    source ./venv/bin/activate
                    fhirmodel publish ./project/profiles --username=$SIMPLIFIER_USER --password=$SIMPLIFIER_PW
                    fhirmodel publish ./project/resources --resource_type=resource --username=$SIMPLIFIER_USER --password=$SIMPLIFIER_PW
                  fi
