#!/bin/bash

# --- NOTE ---
# This entrypoint script is ONLY needed by the Docker container that Jenkins
# uses to execute the IG publisher. The difference between it and the default
# kidsfirstdrc/fhir-ig-publisher:latest entrypoint is that this
# entrypoint deletes the output directories generated by the IG publisher on
# on the host system

# This is needed because the output must be deleted between runs, and it can
# only be deleted by the Docker container since the container has ownership of
# the output.

set -e

# Run publisher with all args passed to the Docker container at runtime
/usr/local/openjdk-8/bin/java -jar "/app/org.hl7.fhir.publisher.jar" "$@"

# Clean up publisher's generated output
echo "Deleting publisher generated output ..."
# Save the files `fhirutil validate` still needs after publisher finishes
mkdir /data/output-temp
mv /data/output/qa.* /data/output-temp
rm -rf /data/output
rm -rf /data/temp
rm -rf /data/template
rm -rf /data/input-cache
mv /data/output-temp /data/output
echo "Finished deleting output"
